### ISSUE TITLE
[Bug]: Error after press "Restart" (to update)

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#13] opened 2024-04-22 08:02 UTC
### What went wrong?

After press "Restart" (to update) i got error:
"Cannot delete old application files.
Please try to run installer again.: 2"

### Version

2.1.9

### Operating System

Win

### Additional information

![image](https://github.com/MrDavidRios/remindr_releases/assets/71985019/ff5b5d8d-026c-4aa2-af36-8157859b6758)

**Comment by MrDavidRios** [comment] 2024-04-22 16:06
This happens when there's another instance of Remindr open while trying to update; this was a bug caused by a mistake in the code that ironically was fixed in 2.1.10.

It should update properly when you kill Remindr in the Task Manager and try to start it up/update again; let me know if it doesn't work for you!

**Closed** 2024-05-07 09:25 UTC
Labels: bug
